config/routes.rb
OneTR::Application.routes.draw do
  resources :rubric_line_items

  resources :rubrics

  resources :users

  resources :positives

  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'users#index'

  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

end

app/models/positive.rb
class Positive < ActiveRecord::Base
  attr_accessible :description, :name, :rubric_line_item_id, :type

  belongs_to :rubric_line_item
  #belongs_to :rubric#, :through => :rubric_line_item
  #belongs_to :teacher#, :through => :rubric, :class_name => "User", :foreign_key => :teacher_id
  #belongs_to :student#, :through => :rubric, :class_name => "User", :foreign_key => :student_id
end

app/controllers/positives_controller.rb
class PositivesController < ApplicationController
  # GET /positives
  # GET /positives.json
  def index
    @positives_given = current_user.teacher? ? current_user.positives.all.sort_by(&:created_at) : []
    @positives_received = current_user.student? ? current_user.positives_received.all.sort_by(&:created_at) : []
    @can_create = current_user.teacher?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positives }
    end
  end

  # GET /positives/1
  # GET /positives/1.json
  def show
    @positive = Positive.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @positive }
    end
  end

  # GET /positives/new
  # GET /positives/new.json
  def new
    @positive = Positive.new
    @rubric_line_item_id = params[:rubric_line_item_id].to_i
    @rubric_line_item = RubricLineItem.find(@rubric_line_item_id)
    @users = Student.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @positive }
    end
  end

  # GET /positives/1/edit
  def edit
    @positive = Positive.find(params[:id])
    @rubric_line_item_id = @positive.rubric_line_item_id
  end

  # POST /positives
  # POST /positives.json
  def create
    @positive = Positive.create!(params[:positive])

    respond_to do |format|
      if @positive.save
        format.html { redirect_to edit_rubric_line_item_path(@positive.rubric_line_item), notice: 'Positive was successfully created.' }
        format.json { render json: @positive, status: :created, location: @positive }
      else
        format.html { render action: "new" }
        format.json { render json: @positive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positives/1
  # PUT /positives/1.json
  def update
    @positive = Positive.find(params[:id])

    respond_to do |format|
      if @positive.update_attributes(params[:positive])
        format.html { redirect_to @positive, notice: 'Positive was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @positive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positives/1
  # DELETE /positives/1.json
  def destroy
    @positive = Positive.find(params[:id])
    @positive.destroy

    respond_to do |format|
      format.html { redirect_to positives_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/positives_helper.rb
module PositivesHelper
end

app/views/positives/_form.html.erb
<%= form_for(@positive) do |f| %>
  <% if @positive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@positive.errors.count, "error") %> prohibited this positive from being saved:</h2>

      <ul>
      <% @positive.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :type, ["Plus", "Plusplus", "Minus"] %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
    <%= f.hidden_field :rubric_line_item_id, :value => @rubric_line_item_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positives/edit.html.erb
<h1>Editing positive</h1>

<%= render 'form' %>

<%= link_to 'Show', @positive %> |
<%= link_to 'Back', positives_path %>

app/views/positives/index.html.erb
<% if !@can_create %>
<h1>Positives Received</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>From</th>
  </tr>

<% @positives_received.each do |positive| %>
  <tr>
    <td><%= positive.created_at.strftime("%Y-%m-%d") %>
    <td><%= positive.description %></td>
    <td><%= positive.rubric_line_item.rubric.teacher.first_name %></td>
  </tr>
<% end %>
</table>

<br />

<% else %>

<h1>Positives Given</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>To</th>
  </tr>

<% @positives_given.each do |positive| %>
  <tr>
    <td><%= positive.created_at.strftime("%Y-%m-%d") %>
    <td><%= positive.description %></td>
    <td><%= positive.rubric_line_item.rubric.student.first_name %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Positive', new_positive_path %>
<% end %>

app/views/positives/new.html.erb
<h1>New positive</h1>

<%= render 'form' %>

<%= link_to 'Back', edit_rubric_line_item_path(@rubric_line_item) %>

app/views/positives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @positive.name %>
</p>

<p>
  <b>Description:</b>
  <%= @positive.description %>
</p>


<%= link_to 'Edit', edit_positive_path(@positive) %> |
<%= link_to 'Back', positives_path %>