config/routes.rb
OneTR::Application.routes.draw do
  resources :rubric_line_items

  resources :rubrics

  resources :users

  resources :positives

  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'users#index'

  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

end

app/models/rubric.rb
class Rubric < ActiveRecord::Base
  attr_accessible :description, :name, :student_id, :teacher_id

  has_many :rubric_line_items

  belongs_to :teacher, :class_name => "User", :foreign_key => "teacher_id"
  belongs_to :student, :class_name => "User", :foreign_key => "student_id"
  belongs_to :template, :class_name => "Rubric", :foreign_key => "template_id"

  def template?
    template_id.nil? && student_id.nil?
  end

  def self.templates_for(user)
    user.rubrics_given.select(&:template?)
  end

  def self.assigned_rubrics_for(user)
    user.rubrics_given.select{|rr| !rr.template?}
  end
end

app/controllers/rubrics_controller.rb
class RubricsController < ApplicationController
  # GET /rubrics
  # GET /rubrics.json
  def index
    @rubrics_given = Rubric.assigned_rubrics_for(current_user)
    @rubrics_received = current_user.rubrics_received

    @templates = Rubric.templates_for(current_user)
    @can_create = current_user.teacher?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rubrics }
    end
  end

  # GET /rubrics/1
  # GET /rubrics/1.json
  def show
    @rubric = Rubric.find(params[:id])
    @rubric_line_items = @rubric.rubric_line_items

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rubric }
    end
  end

  # GET /rubrics/new
  # GET /rubrics/new.json
  def new
    @rubric = Rubric.new
    @users = Student.all
    @template = params[:template]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rubric }
    end
  end

  # GET /rubrics/1/edit
  def edit
    @rubric = Rubric.find(params[:id])
    @users = Student.all
    @rubric_line_items = @rubric.rubric_line_items
  end

  # POST /rubrics
  # POST /rubrics.json
  def create
    @rubric = Rubric.create!(params[:rubric].merge(:teacher_id => current_user.id))
    @rubric_line_items = []

    respond_to do |format|
      if @rubric.save && @rubric_line_items.each(&:save)
        format.html { redirect_to :rubrics, notice: 'Rubric was successfully created.' }
        format.json { render json: @rubric, status: :created, location: @rubric }
      else
        format.html { render action: "new" }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rubrics/1
  # PUT /rubrics/1.json
  def update
    @rubric = Rubric.find(params[:id])

    respond_to do |format|
      if @rubric.update_attributes(params[:rubric])
        format.html { redirect_to @rubric, notice: 'Rubric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rubric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubrics/1
  # DELETE /rubrics/1.json
  def destroy
    @rubric = Rubric.find(params[:id])
    @rubric.destroy

    respond_to do |format|
      format.html { redirect_to rubrics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rubrics_helper.rb
module RubricsHelper
end

app/views/rubrics/_form.html.erb
<%= form_for(@rubric) do |f| %>
  <% if @rubric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rubric.errors.count, "error") %> prohibited this rubric from being saved:</h2>

      <ul>
      <% @rubric.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if !@template %>
    <div class="field">
      <%= f.label :student %><br \>
      <%= f.select "student_id", options_from_collection_for_select(@users, "id", "username") %>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rubrics/edit.html.erb
<h1>Editing rubric</h1>

<%= render 'form' %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>
<% @rubric_line_items.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.description %></td>
    <td><%= link_to 'Edit', edit_rubric_line_item_path(item) %> </td>
    <td></td>
<%end%>

<%= link_to 'Add line item', new_rubric_line_item_path(:rubric_id => @rubric.id) %> |
<%= link_to 'Show', @rubric %> |
<%= link_to 'Back', rubrics_path %>

app/views/rubrics/index.html.erb
<% if @can_create %>
<h1> Your Templates </h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.name %> </td>
    <td><%= template.description %> </td>
    <td><%= link_to 'Show', template %></td>
    <td><%= link_to 'Edit', edit_rubric_path(template) %></td>
    <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Rubrics using this template will not be deleted' } %> </td>
  </tr>
<% end %>
</table>

<h1> Your Rubrics Assigned </h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Student</th>
    <th></th>
    <th></th>
  </tr>

<% @rubrics_given.each do |rubric| %>
  <tr>
    <td><%= rubric.name %></td>
    <td><%= rubric.description %></td>
    <td><%= rubric.student.first_name %></td>
    <td><%= link_to 'Show', rubric %></td>
    <td><%= link_to 'Edit', edit_rubric_path(rubric) %></td>
    <td><%= link_to 'Destroy', rubric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<% else %>
<h1>Rubrics Received</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Teacher</th>
    <th></th>
  </tr>

<% @rubrics_received.each do |rubric| %>
  <tr>
    <td><%= rubric.name %></td>
    <td><%= rubric.description %></td>
    <td><%= rubric.teacher.first_name %></td>
    <td><%= link_to 'Show', rubric %></td>
  </tr>
<% end %>
</table>

<br />
<% end %>
<% if @can_create %>
  <%= link_to 'New Rubric', new_rubric_path %>
  <%= link_to 'New Template Rubric', new_rubric_path(:template => true) %>
<% end %>

app/views/rubrics/new.html.erb
<h1>New rubric</h1>

<%= render 'form' %>

<%= link_to 'Back', rubrics_path %>

app/views/rubrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rubric.name %>
</p>

<p>
  <b>Description:</b>
  <%= @rubric.description %>
</p>

<table>
<% @rubric_line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.name %></td>
    <td><%= line_item.description %></td>
  </tr>
  <% line_item.positives.each do |positive| %>
    <tr>
      <td>
      </td>
      <td>
        <%= positive.description =%>
      </td>
  </tr>
<% end %>
<% end %>
</table>

<%= link_to 'Edit', edit_rubric_path(@rubric) %> |
<%= link_to 'Back', rubrics_path %>