config/routes.rb
OneTR::Application.routes.draw do
  resources :rubric_line_items

  resources :rubrics

  resources :users

  resources :positives

  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'users#index'

  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'

end

app/models/rubric_line_item.rb
class RubricLineItem < ActiveRecord::Base
  attr_accessible :description, :name, :rubric_id

  belongs_to :rubric
  has_many :positives
end

app/controllers/rubric_line_items_controller.rb
class RubricLineItemsController < ApplicationController
  # GET /rubric_line_items
  # GET /rubric_line_items.json
  def index
    @rubric_line_items = RubricLineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rubric_line_items }
    end
  end

  # GET /rubric_line_items/1
  # GET /rubric_line_items/1.json
  def show
    @rubric_line_item = RubricLineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rubric_line_item }
    end
  end

  # GET /rubric_line_items/new
  # GET /rubric_line_items/new.json
  def new
    @rubric_line_item = RubricLineItem.new
    @rubric_id = params[:rubric_id].to_i
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rubric_line_item }
    end
  end

  # GET /rubric_line_items/1/edit
  def edit
    @rubric_line_item = RubricLineItem.find(params[:id])
    @rubric_id = @rubric_line_item.rubric_id
    @positives = @rubric_line_item.positives
  end

  # POST /rubric_line_items
  # POST /rubric_line_items.json
  def create
    @rubric_line_item = RubricLineItem.new(params[:rubric_line_item])

    respond_to do |format|
      if @rubric_line_item.save
        format.html { redirect_to edit_rubric_path(@rubric_line_item.rubric), notice: 'Rubric line item was successfully created.' }
        format.json { render json: @rubric_line_item, status: :created, location: @rubric_line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @rubric_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rubric_line_items/1
  # PUT /rubric_line_items/1.json
  def update
    @rubric_line_item = RubricLineItem.find(params[:id])

    respond_to do |format|
      if @rubric_line_item.update_attributes(params[:rubric_line_item])
        format.html { redirect_to edit_rubric_path(@rubric_line_item.rubric), notice: 'Rubric line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rubric_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubric_line_items/1
  # DELETE /rubric_line_items/1.json
  def destroy
    @rubric_line_item = RubricLineItem.find(params[:id])
    @rubric_line_item.destroy

    respond_to do |format|
      format.html { redirect_to rubric_line_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rubric_line_items_helper.rb
module RubricLineItemsHelper
end

app/views/rubric_line_items/_form.html.erb
<%= form_for(@rubric_line_item) do |f| %>
  <% if @rubric_line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rubric_line_item.errors.count, "error") %> prohibited this rubric_line_item from being saved:</h2>

      <ul>
      <% @rubric_line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <%= f.hidden_field :rubric_id, :value => @rubric_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rubric_line_items/edit.html.erb
<h1>Editing rubric_line_item</h1>

<%= render 'form' %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>
<% @positives.each do |item| %>
  <tr>
    <td><%= item.name %></td>
    <td><%= item.description %></td>
    <td><%= link_to 'Edit', edit_positive_path(item) %> </td>
    <td></td>
<%end%>

<%= link_to 'Add positive', new_positive_path(:rubric_line_item_id => @rubric_line_item.id) %> |
<%= link_to 'Show', @rubric_line_item %> |
<%= link_to 'Back', rubric_line_items_path %>

app/views/rubric_line_items/index.html.erb
<h1>Listing rubric_line_items</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Rubric</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rubric_line_items.each do |rubric_line_item| %>
  <tr>
    <td><%= rubric_line_item.name %></td>
    <td><%= rubric_line_item.description %></td>
    <td><%= rubric_line_item.rubric_id %></td>
    <td><%= link_to 'Show', rubric_line_item %></td>
    <td><%= link_to 'Edit', edit_rubric_line_item_path(rubric_line_item) %></td>
    <td><%= link_to 'Destroy', rubric_line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rubric line item', new_rubric_line_item_path %>

app/views/rubric_line_items/new.html.erb
<h1>New rubric_line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', rubric_line_items_path %>

app/views/rubric_line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @rubric_line_item.name %>
</p>

<p>
  <b>Description:</b>
  <%= @rubric_line_item.description %>
</p>

<p>
  <b>Rubric:</b>
  <%= @rubric_line_item.rubric_id %>
</p>


<%= link_to 'Edit', edit_rubric_line_item_path(@rubric_line_item) %> |
<%= link_to 'Back', rubric_line_items_path %>